#!/usr/bin/env python3
"""
Pentagon numbers
 
Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, 
for which their sum and difference are pentagonal and 
D = |Pk − Pj| is minimised; what is the value of D?
"""

import math

# Let Pn = x
# => x = n * (3n - 1) / 2
# => 2x = 3n^2 - n
# => 3n^2 - n - 2x = 0
#solve quadratic equation
# n= 1 + sqrt(1 + 24x) / 6
# => must be (1 + sqrt(1 + 24x)) % 6 = 0

def is_pentagonal(n):
    return (1 + math.sqrt(1 + 24 * n)) % 6 == 0

i = 0
while True:
    i += 1
    k = i * (3 * i -1) // 2
    for v in range(1, i):
        j = v * (3 * v - 1) // 2
        if is_pentagonal(k - j) and is_pentagonal(k + j):
            print(f'Minimal D is {k -j}, for pentagonal numbers P{i}={k} and P{v}={j}')
            break
    else:
        continue
    break


    